name: 'Publish'
on:
  push:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'npm publish --registry=https://npm.pkg.github.com --scope=@q4justice'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
