name: 'Check'
on:
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Ensure package.json version has been incremented'
        uses: Q4Justice/package-version-check@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-file: 'package.json'
