name: Publish to npm

on:
 push:
    branches:
      - main # Ersetzen Sie 'main' durch den Namen Ihrer Hauptbranch, falls anders

jobs:
 publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14' # Ersetzen Sie '14' durch die gewünschte Node.js-Version
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}